// Set up = This is similar to default tags in html
const express = require('express'); // This is a framework for Node.js
const app = express(); // The variable app is the instance of express server
const router = express.Router(); // The variable router is the instance of express router which is used to create routes (sends back only the data requested)

// Start the web server... app.listen(port number, function)/ *Enter 'node app.js' in the terminal to start the server
app.listen(3000, function() {
    console.log('Listening on port 3000');
});

// Making an api using routes
// Routes are used to handle browser requests. They look like URLs.The difference is that when a browser
// requests a route (URL), it is dynamically generated by the server using a function.

// Get or a regular request when someone goes to http://localhost:3000/hello
// When using a function in a route, we almost always have a parameter or handle a response and request.
app.get("/hello", function(req, res) {
    res.send("<h1>Hello Express</h1>");  // Display 'Hello Express' in the browser when entering localhost:3000/hello
});

// Creating a different route
app.get("/goodbye", function(req, res) {
    res.send("<h1>Goodbye Express!</h1>"); // Display 'Goodbye Express' in the browser when entering localhost:3000/goodbye
});